export const defaultData = {
  heroStats: [
    { value: "27+", label: "Projects"  },
    { value: "90.7%", label: "Uptime"  },
    { value: "7+",  label: "Bots Built"},
    { value: "6+",  label: "Yrs Exp."  },
  ],

  aboutStats: [
    { label: "Years Experience",   value: "6+"  },
    { label: "Clients Served",     value: "25+" },
    { label: "Projects Completed", value: "30+" },
    { label: "Success Rate",       value: "99%" },
  ],

  projects: [
    {
      id: 1, title: "Enterprise Network Monitoring Dashboard",
      category: "Network Engineering",
      description: "Real-time network monitoring dashboard tracking bandwidth usage, latency, and server uptime across multi-region infrastructure for 50+ devices.",
      image: "/projects/project 1.jpg",
      tags: ["Node.js", "React.js", "WebSocket", "Prometheus", "Grafana"],
      icon: "Network",
      highlights: ["99.9% Uptime", "60% Faster Troubleshooting", "24/7 Monitoring"],
      demoURL: "https://portfolio-website-xby4.vercel.app/", githubUrl: "#",
    },
    {
      id: 2, title: "Cloud Infrastructure Automation Platform",
      category: "DevOps",
      description: "Comprehensive automation tool for provisioning and managing cloud infrastructure across AWS and Azure with Infrastructure-as-Code approach.",
      image: "/projects/project 2.jpg",
      tags: ["AWS", "Python", "Terraform", "Ansible", "Docker"],
      icon: "Cloud",
      highlights: ["50+ VPCs Managed", "4hrs → 15min Deployment", "200+ EC2 Instances"],
      demoURL: "https://portfolio-website-xby4.vercel.app/", githubUrl: "#",
    },
    {
      id: 3, title: "Distributed Microservices Platform",
      category: "Full-Stack",
      description: "Microservices-based architecture with load-balanced network infrastructure handling 1000+ requests per day.",
      image: "/projects/project 3.jpg",
      tags: ["Node.js", "Kubernetes", "Redis", "PostgreSQL", "Docker"],
      icon: "Code",
      highlights: ["10K+ Req/min", "99.95% Uptime", "Multi-Cloud"],
      demoURL: "https://white-bay.vercel.app", githubUrl: "#",
    },
    {
      id: 4, title: "Telegram Food Distribution & Payment Bot",
      category: "Bot Development",
      description: "Scalable Telegram bot for automated food ordering system with integrated payment confirmation and real-time database monitoring.",
      image: "/projects/project 6.jpg",
      tags: ["Python", "Telegram API", "PostgreSQL", "Redis", "Stripe"],
      icon: "Bot",
      highlights: ["1000+ Users", "Real-time Updates", "Payment Integration"],
      demoURL: "https://t.me/Chowdome_bot", githubUrl: "#",
    },
    {
      id: 5, title: "VPN & Multi-Site Security Gateway",
      category: "Network Security",
      description: "Enterprise-grade VPN gateway system for secure remote access with 150+ concurrent connections across 5 countries.",
      image: "/projects/project 4.jpg",
      tags: ["OpenVPN", "WireGuard", "Python", "React", "IPSec"],
      icon: "Shield",
      highlights: ["99.8% Uptime", "Zero Breaches", "250+ Connections"],
      demoURL: "https://chip-chop-beta.vercel.app", githubUrl: "#",
    },
    {
      id: 6, title: "Network Diagnostic & Troubleshooting Suite",
      category: "Network Tools",
      description: "Comprehensive network diagnostic toolkit including ping, traceroute, port scanning, DNS analysis, and packet inspection.",
      image: "/projects/project 5.jpg",
      tags: ["Python", "Scapy", "Socket", "Flask API", "React"],
      icon: "Zap",
      highlights: ["Multi-Tool Suite", "PDF/CSV Reports", "API Integration"],
      demoURL: "https://blue-ark-frontend.vercel.app", githubUrl: "#",
    },
  ],

  skills: [
    { name: "HTML5",        level: 95, category: "frontend",   years: 6 },
    { name: "CSS3",         level: 95, category: "frontend",   years: 6 },
    { name: "JavaScript",   level: 90, category: "frontend",   years: 5 },
    { name: "React.js",     level: 90, category: "frontend",   years: 4 },
    { name: "Next.js",      level: 85, category: "frontend",   years: 3 },
    { name: "TypeScript",   level: 80, category: "frontend",   years: 3 },
    { name: "Tailwind CSS", level: 95, category: "frontend",   years: 3 },
    { name: "Python",       level: 95, category: "backend",    years: 5 },
    { name: "Node.js",      level: 90, category: "backend",    years: 4 },
    { name: "Django",       level: 95, category: "backend",    years: 4 },
    { name: "Express.js",   level: 85, category: "backend",    years: 3 },
    { name: "FastAPI",      level: 80, category: "backend",    years: 2 },
    { name: "PostgreSQL",   level: 85, category: "database",   years: 4 },
    { name: "MongoDB",      level: 80, category: "database",   years: 3 },
    { name: "MySQL",        level: 80, category: "database",   years: 3 },
    { name: "AWS",          level: 85, category: "networking", years: 3 },
    { name: "Docker",       level: 85, category: "networking", years: 3 },
    { name: "Cloudflare",   level: 75, category: "networking", years: 2 },
    { name: "Wireshark",    level: 80, category: "networking", years: 4 },
    { name: "Telegram Bot", level: 95, category: "bots",       years: 4 },
    { name: "Discord Bot",  level: 90, category: "bots",       years: 3 },
    { name: "Trading Bots", level: 85, category: "bots",       years: 2 },
    { name: "Git",          level: 95, category: "tools",      years: 6 },
    { name: "GitHub",       level: 95, category: "tools",      years: 5 },
    { name: "CI/CD",        level: 70, category: "tools",      years: 3 },
  ],
}
